# site settings
title: Sean Ryan
subtitle: The Portfolio of
email: designingsean@gmail.com
description: ''
baseurl: '' # the subpath of your site, e.g. /blog
url: # the base hostname & protocol for your site
author:

# homepage tiles
tiles-source: pages # accepts "posts" or "pages"
tiles-count: 6

# social setting
github_url: https://github.com/designingsean
linkedin_url: https://www.linkedin.com/in/designingsean

# build settings
markdown: kramdown

sass:
  style: compressed

collections:
  casestudies:
    output: true
    permalink: /:collection/:name